# Generated by Django 3.2.7 on 2022-02-07 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_auto_20220208_0301'),
        ('membership', '0002_usermembership_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='courses.course', verbose_name='Курс'),
        ),
    ]
