# Generated by Django 3.2.7 on 2022-02-08 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_auto_20220209_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermembership',
            name='course_membership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_membership', to='membership.coursemembership', verbose_name='Подписка на курс'),
        ),
        migrations.AlterField(
            model_name='usermembership',
            name='package_membership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_package', to='membership.package', verbose_name='Пакет подписки'),
        ),
    ]
