# Generated by Django 3.2.7 on 2022-02-09 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0006_auto_20220209_0542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermembership',
            name='package_membership',
        ),
        migrations.CreateModel(
            name='RegisterRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=50, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=200, verbose_name='Почта')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
                ('promo_code', models.CharField(max_length=50, unique=True, verbose_name='Промокод')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачен?')),
                ('package_membership', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='membership.package', verbose_name='Пакет')),
            ],
            options={
                'verbose_name': 'Заявка на регистрацию',
                'verbose_name_plural': 'Заявки на регистрации',
            },
        ),
        migrations.AddField(
            model_name='usermembership',
            name='register_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='membership.registerrequest', verbose_name='Форма заявки'),
        ),
    ]
