# Generated by Django 3.2.7 on 2022-02-09 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0008_alter_registerrequest_promo_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerrequest',
            name='package_membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='membership.package', verbose_name='Пакет'),
        ),
    ]
