# Generated by Django 3.2.7 on 2022-02-09 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0009_alter_registerrequest_package_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermembership',
            name='course_membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_membership', to='membership.coursemembership', verbose_name='Подписка на курс'),
        ),
    ]
