# Generated by Django 3.2.7 on 2022-02-09 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0010_alter_usermembership_course_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerrequest',
            name='email',
            field=models.EmailField(max_length=200, unique=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='registerrequest',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Оплачено?'),
        ),
    ]
