# Generated by Django 3.2.7 on 2022-02-09 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_auto_20220208_0301'),
        ('webinar', '0006_auto_20220116_0047'),
        ('masterclass', '0004_auto_20220116_0001'),
        ('membership', '0011_auto_20220209_0625'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebinarPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.package', verbose_name='Пакет')),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webinar.webinar', verbose_name='Вебинар')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MasterClassPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masterclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterclass.masterclass', verbose_name='Мастер-Класс')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.package', verbose_name='Пакет')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CoursePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Курс')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.package', verbose_name='Пакет')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
