# Generated by Django 3.2.7 on 2022-02-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0014_auto_20220210_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(blank=True, help_text='Поле не обязательное, если оставить пустым код сгенерируется автоматически', max_length=50, unique=True, verbose_name='Купон/Промокод'),
        ),
    ]
