# Generated by Django 3.2.7 on 2022-02-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0016_auto_20220210_2258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursemembership',
            options={'verbose_name': 'Пакет курса', 'verbose_name_plural': 'Пакеты курсов'},
        ),
        migrations.AddField(
            model_name='coupon',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Цена со скидкой'),
        ),
    ]
