# Generated by Django 3.2.7 on 2022-02-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0017_auto_20220210_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Заполняется автоматически после сохранения', max_digits=9, verbose_name='Цена со скидкой'),
        ),
    ]
