# Generated by Django 3.2.7 on 2022-02-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0018_alter_coupon_final_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Заполняется автоматически после сохранения', max_digits=9, verbose_name='Цена со скидкой'),
        ),
    ]
