# Generated by Django 3.2.7 on 2022-02-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0019_alter_coupon_final_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerrequest',
            name='payment_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID оплаты'),
        ),
        migrations.AddField(
            model_name='registerrequest',
            name='payment_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка оплаты'),
        ),
    ]
