# Generated by Django 3.2.7 on 2022-02-10 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0020_auto_20220211_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerrequest',
            name='promo_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Промокод'),
        ),
    ]
