# Generated by Django 3.2.7 on 2022-02-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0021_alter_registerrequest_promo_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='valid_from',
            field=models.DateTimeField(verbose_name='Действует от'),
        ),
    ]
