# Generated by Django 3.2.7 on 2022-02-12 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterclass', '0004_auto_20220116_0001'),
        ('webinar', '0006_auto_20220116_0047'),
        ('article', '0003_auto_20220209_0544'),
        ('courses', '0018_auto_20220212_0547'),
        ('membership', '0023_articlepackage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepackage',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles_compound', to='article.article', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='coursepackage',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_compound', to='courses.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='masterclasspackage',
            name='masterclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masterclasses_compound', to='masterclass.masterclass', verbose_name='Мастер-Класс'),
        ),
        migrations.AlterField(
            model_name='webinarpackage',
            name='webinar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webinars_compound', to='webinar.webinar', verbose_name='Вебинар'),
        ),
    ]
