# Generated by Django 3.2.7 on 2022-02-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0024_auto_20220212_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerrequest',
            name='expire_date',
            field=models.DateField(blank=True, null=True, verbose_name='Срок истечения'),
        ),
        migrations.AddField(
            model_name='registerrequest',
            name='paid_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата покупки'),
        ),
        migrations.AddField(
            model_name='registerrequest',
            name='paid_price',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Оплаченная сумма'),
        ),
        migrations.AddField(
            model_name='registerrequest',
            name='status',
            field=models.CharField(choices=[('used', 'used'), ('expired', 'expired')], default='used', max_length=32, verbose_name='Статус подписки'),
        ),
        migrations.AddField(
            model_name='registerrequest',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип пакета'),
        ),
    ]
