# Generated by Django 3.2.7 on 2022-02-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0025_auto_20220213_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerrequest',
            name='paid_price',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Конечная сумма'),
        ),
    ]
