# Generated by Django 3.2.7 on 2022-02-22 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0027_auto_20220222_2147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registerrequestpayment',
            options={'verbose_name': 'Оплаты пользователей'},
        ),
        migrations.RenameField(
            model_name='registerrequestpayment',
            old_name='reqister_request',
            new_name='register_request',
        ),
        migrations.AddField(
            model_name='registerrequestpayment',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Оплачено'),
        ),
        migrations.AlterField(
            model_name='usermembership',
            name='register_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rg_membership', to='membership.registerrequest', verbose_name='Форма заявки'),
        ),
    ]
