# Generated by Django 3.2.7 on 2022-03-18 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0030_auto_20220227_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermembership',
            name='course_membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership.coursemembership', verbose_name='Подписка на курс'),
        ),
    ]
