# Generated by Django 3.2.7 on 2022-03-18 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0006_auto_20220116_0047'),
        ('courses', '0021_auto_20220316_0244'),
        ('article', '0005_auto_20220217_2319'),
        ('masterclass', '0004_auto_20220116_0001'),
        ('membership', '0031_alter_usermembership_course_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepackage',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.article', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='coursepackage',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='coursepackage',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_compound', to='membership.package', verbose_name='Пакет'),
        ),
        migrations.AlterField(
            model_name='masterclasspackage',
            name='masterclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterclass.masterclass', verbose_name='Мастер-Класс'),
        ),
        migrations.AlterField(
            model_name='webinarpackage',
            name='webinar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webinar.webinar', verbose_name='Вебинар'),
        ),
    ]
