# Generated by Django 3.2.7 on 2022-01-15 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0006_mentor_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('title_ky', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='MasterClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('title_ky', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True, verbose_name='Подзаголовок')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Слаг')),
                ('image', models.FileField(blank=True, null=True, upload_to='images/', verbose_name='Изображение')),
                ('video', models.URLField(blank=True, null=True, verbose_name='Видео')),
                ('overview', models.TextField(verbose_name='Описание')),
                ('overview_ru', models.TextField(null=True, verbose_name='Описание')),
                ('overview_ky', models.TextField(null=True, verbose_name='Описание')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('duration', models.CharField(max_length=50, verbose_name='Продолжительность')),
                ('duration_ru', models.CharField(max_length=50, null=True, verbose_name='Продолжительность')),
                ('duration_ky', models.CharField(max_length=50, null=True, verbose_name='Продолжительность')),
                ('new', models.BooleanField(default=True, verbose_name='Новое')),
                ('week', models.DateTimeField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_created', to='user.mentor', verbose_name='Куратор')),
                ('themes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master', to='masterclass.theme', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Мастер Класс',
                'verbose_name_plural': 'Мастер Классы',
                'ordering': ('-created',),
            },
        ),
    ]
