# Generated by Django 3.2.7 on 2022-01-15 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterclass', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masterclass',
            options={'ordering': ('-created',), 'verbose_name': 'Мастер-Класс', 'verbose_name_plural': 'Мастер-Классы'},
        ),
        migrations.CreateModel(
            name='MasterClassReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Отзыв')),
                ('video', models.URLField(verbose_name='Видео')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('masterclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='masterclass.masterclass', verbose_name='Мастер-Класс')),
            ],
            options={
                'verbose_name': 'Отзыв про мастер-класс',
                'verbose_name_plural': 'Отзывы про мастер-классы',
                'ordering': ('-created',),
            },
        ),
    ]
