# Generated by Django 3.2.7 on 2022-01-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterclass', '0002_auto_20220115_2145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masterclassreview',
            options={'ordering': ('-created',), 'verbose_name': 'Отзыв про Мастер-Класс', 'verbose_name_plural': 'Отзывы про Мастер-Классы'},
        ),
        migrations.AddField(
            model_name='masterclass',
            name='subtitle_ky',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='masterclass',
            name='subtitle_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Подзаголовок'),
        ),
    ]
