# Generated by Django 3.2.7 on 2022-01-15 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterclass', '0003_auto_20220115_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterclass',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='slug',
        ),
    ]
