# Generated by Django 3.2.7 on 2022-02-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20220209_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='new',
            field=models.BooleanField(default=True, verbose_name='Новое?'),
        ),
    ]
