# Generated by Django 3.2.7 on 2022-02-17 17:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0004_article_new'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecomment',
            options={'verbose_name': 'Статья/Комментарий', 'verbose_name_plural': 'Статья/Комментарии'},
        ),
        migrations.RemoveField(
            model_name='articlecomment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='articlecomment',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 2, 17, 17, 19, 1, 542203, tzinfo=utc), verbose_name='Создан'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='user_article_comment_likes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи, которым нравится комментарий'),
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='total_likes',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Кол-во лайков'),
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_comments', to='article.article', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_article_comments', to='user.customuser', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='text',
            field=models.TextField(verbose_name='Комментарий'),
        ),
        migrations.CreateModel(
            name='ArticleCommentReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Ответ на комментарий')),
                ('total_likes', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Кол-во лайков')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_article_comment_replies', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_comment_replies', to='article.articlecomment', verbose_name='Коммент')),
                ('likes', models.ManyToManyField(blank=True, related_name='user_article_comment_reply_likes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи, которым нравится ответ на комментарий')),
            ],
            options={
                'verbose_name': 'Статья/Ответ на комментарий',
                'verbose_name_plural': 'Статьи/Ответы на комментарии',
            },
        ),
    ]
