# Generated by Django 3.2.7 on 2022-01-15 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration_months',
            field=models.CharField(default='asdasd', max_length=200, verbose_name='Длительность в месяцах'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Отзыв')),
                ('video', models.URLField(verbose_name='Видео')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='courses.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Отзыв про курс',
                'verbose_name_plural': 'Отзывы про курсы',
                'ordering': ('-created',),
            },
        ),
    ]
