# Generated by Django 3.2.7 on 2022-01-19 11:40

import courses.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20220118_2312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ('-created',), 'verbose_name': 'Файл', 'verbose_name_plural': 'Файлы'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('-created',), 'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterModelOptions(
            name='text',
            options={'ordering': ('-created',), 'verbose_name': 'Текст', 'verbose_name_plural': 'Тексты'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ('-created',), 'verbose_name': 'Видео', 'verbose_name_plural': 'Видео'},
        ),
        migrations.RemoveField(
            model_name='content',
            name='module',
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('order', courses.fields.OrderField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.module', verbose_name='Модуль')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='content',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='courses.lesson', verbose_name='Урок'),
            preserve_default=False,
        ),
    ]
