# Generated by Django 3.2.7 on 2022-01-19 12:11

import courses.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20220119_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='order',
            field=courses.fields.OrderField(blank=True, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=courses.fields.OrderField(blank=True, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='module',
            name='order',
            field=courses.fields.OrderField(blank=True, verbose_name='Порядок'),
        ),
    ]
