# Generated by Django 3.2.7 on 2022-02-07 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_rename_content_text_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ('order',), 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
    ]
