# Generated by Django 3.2.7 on 2022-02-07 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_course_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='description',
        ),
        migrations.RemoveField(
            model_name='module',
            name='description_ky',
        ),
        migrations.RemoveField(
            model_name='module',
            name='description_ru',
        ),
    ]
