# Generated by Django 3.2.7 on 2022-02-07 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0014_auto_20220208_0038'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineCourseProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Оффлайн курс',
                'verbose_name_plural': 'Оффлайн курсы',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('courses.course',),
        ),
        migrations.AlterModelOptions(
            name='coursereview',
            options={'ordering': ('-created',), 'verbose_name': 'Курс отзыв', 'verbose_name_plural': 'Курс отзывы'},
        ),
        migrations.CreateModel(
            name='CourseComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='автор')),
                ('likes', models.ManyToManyField(blank=True, related_name='user_comments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи, которым нравится комментарий')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
