# Generated by Django 3.2.7 on 2022-02-07 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0015_auto_20220208_0211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursereview',
            options={'ordering': ('-created',), 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AddField(
            model_name='coursecomment',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course_comments', to='courses.course', verbose_name='Курс'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursecomment',
            name='total_likes',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Кол-во лайков'),
        ),
        migrations.AlterField(
            model_name='coursecomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='coursecomment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_comments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи, которым нравится комментарий'),
        ),
        migrations.CreateModel(
            name='CommentReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Ответ на комментарий')),
                ('total_likes', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Кол-во лайков')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='courses.coursecomment', verbose_name='Коммент')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_replies', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи, которым нравится ответ на комментарий')),
            ],
            options={
                'verbose_name': 'Ответ на комментарий',
                'verbose_name_plural': 'Ответы на комментарии',
            },
        ),
    ]
