# Generated by Django 3.2.7 on 2022-02-17 17:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_auto_20220212_0547'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentreply',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 2, 17, 17, 0, 25, 515203, tzinfo=utc), verbose_name='Создан'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coursecomment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
    ]
