# Generated by Django 3.2.7 on 2022-02-17 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_auto_20220217_2300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentreply',
            options={'verbose_name': 'Курс/Ответ на комментарий', 'verbose_name_plural': 'Курс/Ответы на комментарии'},
        ),
        migrations.AlterModelOptions(
            name='coursecomment',
            options={'verbose_name': 'Курс/Комментарий', 'verbose_name_plural': 'Курс/Комментарии'},
        ),
    ]
