# Generated by Django 3.2.7 on 2022-03-18 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_auto_20220316_0244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='title_ky',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='title_ru',
        ),
    ]
