# Generated by Django 3.2.7 on 2022-04-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_courseprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseprogress',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
