# Generated by Django 3.2.7 on 2022-04-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_remove_courseprogress_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseprogress',
            name='data',
            field=models.JSONField(default='{}'),
        ),
    ]
