# Generated by Django 3.2.7 on 2022-01-14 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_helpinchoosing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='helpinchoosing',
            options={'verbose_name': 'Помощь в выборе', 'verbose_name_plural': 'Помощь в выборе'},
        ),
    ]
