# Generated by Django 3.2.7 on 2022-01-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_companyreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='short_bio',
            field=models.CharField(default='short bio', max_length=200, verbose_name='Короткое БИО'),
            preserve_default=False,
        ),
    ]
