# Generated by Django 3.2.7 on 2022-01-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_mentor_short_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='short_bio_ky',
            field=models.CharField(max_length=200, null=True, verbose_name='Короткое БИО'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='short_bio_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Короткое БИО'),
        ),
    ]
