# Generated by Django 3.2.7 on 2022-04-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_email_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='promo_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
