# Generated by Django 3.2.7 on 2022-01-15 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0002_auto_20220115_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebinarReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Отзыв')),
                ('video', models.URLField(verbose_name='Видео')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='webinar.webinar', verbose_name='Вебинар')),
            ],
            options={
                'verbose_name': 'Отзыв про вебинар',
                'verbose_name_plural': 'Отзывы про вебинары',
                'ordering': ('-created',),
            },
        ),
    ]
