# Generated by Django 3.2.7 on 2022-01-15 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0004_auto_20220115_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webinar',
            name='slug',
        ),
    ]
