# Generated by Django 3.2.7 on 2022-01-15 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_companyreview'),
        ('webinar', '0005_remove_webinar_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webinar',
            name='author',
        ),
        migrations.AddField(
            model_name='webinar',
            name='mentor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webinars', to='user.mentor', verbose_name='Куратор'),
        ),
    ]
