# Generated by Django 3.2.7 on 2022-01-15 14:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0006_mentor_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Заголовок')),
                ('title_ky', models.CharField(max_length=200, null=True, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True, verbose_name='Подзаголовок')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('description', models.TextField(verbose_name='Про путешествие')),
                ('description_ru', models.TextField(null=True, verbose_name='Про путешествие')),
                ('description_ky', models.TextField(null=True, verbose_name='Про путешествие')),
                ('duration', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Продолжительность в днях')),
                ('concept_for_travel', models.TextField(verbose_name='Концепция путешествия')),
                ('concept_for_travel_ru', models.TextField(null=True, verbose_name='Концепция путешествия')),
                ('concept_for_travel_ky', models.TextField(null=True, verbose_name='Концепция путешествия')),
                ('new', models.BooleanField(default=True, verbose_name='Новое')),
                ('sold_out', models.BooleanField(default=False, verbose_name='Расспродан')),
                ('week', models.DateTimeField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('seats', models.PositiveIntegerField(default=0, verbose_name='Кол-во мест')),
            ],
            options={
                'verbose_name': 'Путешествие',
                'verbose_name_plural': 'Путешествия',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='TravelCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Категория путешествия',
                'verbose_name_plural': 'Категории путешествий',
            },
        ),
        migrations.CreateModel(
            name='TravelProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Заголовок')),
                ('title_ky', models.CharField(max_length=200, null=True, verbose_name='Заголовок')),
                ('body', models.TextField(verbose_name='Описание')),
                ('body_ru', models.TextField(null=True, verbose_name='Описание')),
                ('body_ky', models.TextField(null=True, verbose_name='Описание')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('day', models.PositiveIntegerField(default=1, verbose_name='День')),
                ('adventure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='adventure.travel', verbose_name='Путешествие')),
            ],
            options={
                'verbose_name': 'Программа Путешествия',
                'verbose_name_plural': 'Программы Путешествий',
                'ordering': ('day',),
            },
        ),
        migrations.CreateModel(
            name='TravelParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('adventure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_participants', to='adventure.travel', verbose_name='Путешествие')),
            ],
            options={
                'verbose_name': 'Участник путешествия',
                'verbose_name_plural': 'Участники путешествий',
            },
        ),
        migrations.AddField(
            model_name='travel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='travels', to='adventure.travelcategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='travel',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_adventures', to='user.mentor', verbose_name='Куратор'),
        ),
        migrations.CreateModel(
            name='Peculiarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Заголовок')),
                ('title_ky', models.CharField(max_length=200, null=True, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('description_ru', models.TextField(null=True, verbose_name='Описание')),
                ('description_ky', models.TextField(null=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='travel_peculiarity', verbose_name='Изображение')),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peculiarities', to='adventure.travel', verbose_name='Путешествие')),
            ],
            options={
                'verbose_name': 'Особенность и Эмоция',
                'verbose_name_plural': 'Особенности и Эмоции',
            },
        ),
    ]
