# Generated by Django 3.2.7 on 2022-01-18 19:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0004_auto_20220115_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 18, 19, 32, 27, 673427, tzinfo=utc), verbose_name='Дата окончания'),
            preserve_default=False,
        ),
    ]
