# Generated by Django 3.2.7 on 2022-03-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0005_travel_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='travels/', verbose_name='Изображение'),
        ),
    ]
